### PR TITLE
Make code of conduct link visible

### PR DESCRIPTION
**Pull request by lboynton**
Couldn't go with white, so went with not-quite-black.
coc-link

### CODE REVIEW

**Comment by asgrim** [comment]
why couldn't you go with white? o_O

**Comment by lboynton** [comment]
Because then it wouldn't stand out as a link against the white text. It needs to be different.

**Comment by asgrim** [comment]
oh I see, I thought there was some actual limitation :)

**Comment by asgrim** [comment]
deployed, thanks @lboynton

**Pull request merged**
